build-Rchive try  to presist  R package binary to docker host

diff --git a/rlib b/rlib
--- a/rlib
+++ b/rlib
@@ -5,33 +5,63 @@ set -o errexit
 
 declare  -r  Rbin="R"  
 declare  -r  local_rlib_path=/usr/lib/${Rbin}  
-declare  -r  Rzip="R.zip"
+declare  -r  Rzip="R.zip" 
+
 [[  -n $(command -v ${Rbin})  ]]  ||  { 
-    echo  -e "fail :  cannot found  R bin"
+    echo  -e "fail :  cannot found  R binaries"
     exit $? 
 } 
 [[ -d ${local_rlib_path} ]]   ||  { 
-    echo -e  "cannot found  path"
+    echo -e  "cannot found  R lib package" 
     exit $? 
 } 
 
-echo -e "Everything is OK  [ ready to go ]" 
 
-compress ()  {  
+buildRchive ()  {   
     [[  -n  $(zip -r ${Rzip} ${local_rlib_path}) ]]  && {  
-        echo -e  "compressed "
+        echo -e  "[zip]  Archive  R lib packages "
     } ||  {  
-        echo -e "fail to compress" 
+        echo -e "[zip] fail $?"  
         exit $?  
     }
 }
 
 dispatch () {  
  
+    local location_path=${1}  
+
     [[ -f ${Rzip} ]]  ||  {   
-        echo -e "compress R zip  not found" 
+        echo -e "trying to looking  for ${Rzip}\n [ not found ]" 
+        echo -e "use  $0 build-Rchive"  
         exit $?  
-    }      
+    }   
+    
+   [[  -d  ${location_path} ]]  ||  {  
+       echo -e  "Inexistant  ${1}  directory"
+       exit $? 
+   } 
 
-
+    # start decompressing 
+    #+ that overwriting the existant  
+    unzip   -o ${Rbin} -d   ${location_path}
+    [[ $? -eq 0  ]]  &&  {
+        echo  -e  "dispatch done"
+        exit $? 
+    }
+    echo -e "error while dispatching  to ${location_path} " 
+    exit -1 
 } 
+
+case   $1  in  
+    "build-Rchive")  
+        buildRchive  
+        ;;
+    "dispatch" ) 
+        dispatch  $2
+        ;;
+    *) 
+        echo -e "undefine flags" 
+        exit 2 
+        ;;
+esac  
+ 
