restructure  folders and  moving out dispatcher to UPATH 	-> no need to be root anymore  to execute it 	-> update  $PATH

diff --git a/UPATH b/UPATH
--- a/UPATH
+++ b/UPATH
@@ -1,23 +1,22 @@
 #!/bin/bash  
 #author :  Umar aka jukoo  <j_umar@outlook.fr> 
-#This script for  mac and gnu/linux Operating  system   
-#YOU NEED TO EXECUTE THIS AS ROOT  CHEF 
+#This script is  for unix   operating system like 
+#Download  only  scripts source  file  and  update $PATH  
 
 set -o  errexit  
  
 declare -a mains_srcipts    
 declare -r dns_test="one.one.one.one"
 declare -r src="scripts/"
-declare -r remote_repo_url="https://raw.githubusercontent.com/avalanche-org/Gen_Assoc/master/${src}"
+declare -r branch="stable"
+declare -r remote_repo_url="https://raw.githubusercontent.com/avalanche-org/Gen_Assoc/${branch}/${src}"
 declare -r ubin="/usr/bin/" 
 declare -r defC="\033[0m"  
 declare -r rootuid=$((0x00)) 
- 
-[[  ${rootuid} -ne ${UID} ]] &&  {
-    echo -e  "Sorry !! you need to be root to  proceed "  
-    exit   ${UID}  
-}
+declare -r sh_version_min=4 
 
+[[  ${BASH_VERSINFO}  -gt ${sh_version} ]]  &&  echo -e "*"  ||  echo -e "your  Bash is out of date  bash v4^ is required" 
+ 
 mains_srcipts=( 
     "mtdt.R"
     "summary.R"
@@ -30,65 +29,50 @@ has_command () {
         return $((0x00)) 
     } || {  
         echo  -e "\033[1;33m Warrning  on line  $LINENO : this $1 command is not available in your system\033[0m"
-        return $((0x001)) 
+        exit  3 
     }
 }
 
-
-is_internet_available () {
+internet::connectivity () {
     has_command  wget
     echo -e  "... testing  connexion"
     `wget -q  --spider   ${dns_test}` 
     test  $? -eq 0  && { 
-        echo -e  "Online !"
+        echo -e  "\x1b[1;32m * Online ${defC}"
         return  $? 
     }||{
-        echo -e "Offline  mode " 
+        echo -e "\x1b[1;33m * Offline ${defC}" 
         return  $? 
     }
 }
 
-automove  () {
-    local path 
-    [[ -n  $1 ]] && path=$1 || path=""
-    for script in ${mains_srcipts[@]} ; do 
-        [[  -f  ${path}${script} ]]  &&  {
-            echo -e "moving  ${path}${script} \t ->  ${ubin}"  
-            `chmod +x  ${path}${script}`
-            sleep 0.3
-            if  [[ -n ${path}  ]] ; then 
-                `cp ${path}${script}  ${ubin}` 
-            else  
-                `mv  ${path}${script}  ${ubin}` 
-            fi 
-             test  $? -eq 0 ||  echo  -e "fail  to move  no root permission !! "  
-            
-        }|| echo  -e "not  found"
-    done    
+update::global::path  () {
+    echo -e  PATH=${PATH}:`pwd`  >> ~/.bashrc  
 }
 
 download_srcipts  () { 
     has_command wget 
     case  $1  in 
         "--remote")  
-            is_internet_available 
+            internet::connectivity
             test $? -eq 0  || {
+                exit_status=$? 
                 echo -e "require  internet unless  you found script folder in path system "
-                exit $?  
+                exit $exit_status
             }
             for  script  in ${mains_srcipts[@]}   ;do 
-                echo  -e "\033[1;34m + Dowloading  $script from source$defC"
+                echo  -e "\033[1;34m + Dowloading  $script from source $defC"
                 `wget ${remote_repo_url}${script} --quiet`
-                test  $? -ne 0  &&  {
+                [[ $? -ne 0 ]]  &&  {
                     echo -e "-\033[1;31m fail to download  $script $defC"
+                    exit 2  
                 }||{
                     echo -e "-\033[1;32m $script [ downloaded ]  $defC"
                 } 
             done
-            automove 
+            update::global::path
             ;;
         *)
-            automove  $src  
 
 esac 
 }
@@ -98,6 +82,11 @@ esac
  
 if [[ -n  $1 ]] ;then 
     download_srcipts  $1  
-else 
-    download_srcipts  
-fi      
+else  
+   cat  << eof
+only  one flag is available   it used to  to download   main scripts source without clonning again
+
+params : 
+--remote
+eof
+fi 
